pipeline {
    agent { 
        label 'eclipse'
    }

    stages {
        stage('Filter') {
            when {
                anyOf {
                    branch 'main'
                    branch 'staging'
                }
            }

            steps {
                script {
                    // Get list of changes from last successful build
                    def changeLogSets = currentBuild.changeSets
                    def changedFiles = []
                    changeLogSets.each { set ->
                        set.each { entry ->
                            entry.affectedFiles.each { file ->
                                changedFiles.add(file.path)
                            }
                        }
                    }

                    // Proceed if changes in directory
                    def proceed = changedFiles.any { it.startsWith('server/') }

                    if (!proceed) {
                        error('No changes in server, skipping deploy.')
                    }
                }
            }
        }

        stage('Install') {
            when {
                anyOf {
                    branch 'main'
                    branch 'staging'
                }
            }

            steps {
                echo 'Installing dependencies..'

                sh '''
                    for item in ./* ./.*; do
                        if [ "$item" != "./server" ] && [ "$item" != "./." ] && [ "$item" != "./.." ]; then
                            rm -rf "$item";
                        fi;
                    done

                    cd server

                    bun i || true
                '''
            }
        }

//         stage('Build') {
//             when {
//                 anyOf {
//                     branch 'main'
//                     branch 'staging'
//                 }
//             }
//
//             steps {
//                 echo 'Building..'
//
//                 sh '''
//                     cd server
//                     bun run build || true
//                 '''
//             }
//         }

        stage('Deploy') {
            when {
                anyOf {
                    branch 'main'
                    branch 'staging'
                }
            }

            environment {
                DOPPLER_TOKEN = credentials("""${sh(
                    returnStdout: true,
                    script: '''
                        if [ "$BRANCH_NAME" = "staging" ]; then
                            echo e078650d-c49c-4899-bd0d-e06b3a137864;
                        else
                            echo bf6cfc2c-9668-485b-9574-6d58efd813c3;
                        fi
                    '''
                )}""")
            }

            steps {
                script {
                    if (env.BRANCH_NAME == 'staging') {
                        env.DEPLOY_PATH = '/home/jenkins/iUnstable0_Personal-Website/Staging'
                        env.PM2_NAME = "@iUnstable0/Personal-Website/Staging-Server"
                        env.BUN_COMMAND = 'staging'
                    } else {
                        env.DEPLOY_PATH = '/home/jenkins/iUnstable0_Personal-Website/Main'
                        env.PM2_NAME = "@iUnstable0/Personal-Website/Server"
                        env.BUN_COMMAND = 'start'
                    }
                }

                echo 'Deploying....'

                sh '''
                    if pm2 list | grep -q "${PM2_NAME}"; then
                        pm2 stop "${PM2_NAME}";
                    fi

                    mkdir -p ${DEPLOY_PATH};

                    rsync -aP server/ ${DEPLOY_PATH}/Server/;

                    if pm2 list | grep -q "${PM2_NAME}"; then
                        DOPPLER_TOKEN=${DOPPLER_TOKEN} pm2 restart "${PM2_NAME}" --update-env;
                    else
                        cd ${DEPLOY_PATH}/Server;
                        DOPPLER_TOKEN=${DOPPLER_TOKEN} FORCE_COLOR=1 pm2 start "bun run ${BUN_COMMAND}" --name "${PM2_NAME}";
                    fi
                '''

                sh 'rm -rf *;'
            }
        }
    }
}