pipeline {
    agent { 
        label 'iunstable0_personal-website'
    }

    stages {
        stage('Install') {
            // when {
            //     branch 'main'
            // }

            steps {
                echo 'Installing dependencies..'

                sh 'cd server && pnpm install'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'

                sh 'cd server && pnpm build'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'

                sh 'rsync -av --remove-source-files server/ /home/deployments/iUnstable0_Personal-Website/Server/'
                sh 'mv .env* /home/deployments/iUnstable0_Personal-Website/Server/'
            }
        }
    }
}