pipeline {
    agent { 
        label 'iunstable0_personal-website'
    }

    stages {
        stage('Install') {
            // when {
            //     branch 'main'
            // }

            steps {
                echo 'Installing dependencies..'

                sh 'rm -rf node_modules ci-archive website package.json package-lock.json .gitignore .idea'
                sh 'cd server && pnpm install'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'

                sh 'cd server && pnpm build'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'

                sh 'mkdir -p /home/deployments/iUnstable0_Personal-Website/Main'
                sh 'mv .env* /home/deployments/iUnstable0_Personal-Website/Main/'

                sh 'rsync -aP server/ /home/deployments/iUnstable0_Personal-Website/Main/Server/'
                sh 'mv server/.env* /home/deployments/iUnstable0_Personal-Website/Main/Server/'

                sh 'rm -rf *'
            }
        }
    }
}